### ISSUE TITLE
Ubuntu 14.04, OpenSSL, Python 2.7.6 and requests

### ISSUE THREAD

**Issue by daaray** [caktus/django-project-template#179]
Copying and pasting some notes from pressweb project.  

*However, another round of issues has cropped up and we are working through them. We provision on Ubuntu 14.04, which by default comes with python 2.7.6. Now that we are using SSL to serve the site, a combination of OpenSSL, requests, and boto is causing an SSLError on downloading the packaged zipfiles of media:*

*SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL
 routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure*

*I went back to staging and replicated the issue there as well. Various resources [(example)](https://github.com/coursera-dl/coursera/issues/330) indicate that upgrading the system python to 2.7.9 is an appropriate solution to this issue.* 

`conf/salt/project.venv.sls` changes

```
deadsnakes-python2.7:
  pkgrepo.managed:
    - humanname: Deadsnakes PPA for 2.7
    - ppa: fkrull/deadsnakes-python2.7

python-pkgs:
  pkg:
    - installed
    - names:
      - python{{ pillar['python_version'] }}
      - python{{ pillar['python_version'] }}-dev
    - require:
      - pkgrepo: deadsnakes-python2.7
```

TL;DR: If we have projects on Python2.x, we likely need a path to upgrade to 2.7.9
